services:
  mimir:
    build: .
    ports:
      - "${MIMIR_PORT}:8080"
    command: ["-config.file=/etc/mimir.yaml", "-config.expand-env=true"]
    environment:
      - MINIO_URL=${MINIO_URL}
      - MINIO_USER=${MINIO_USER}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
      - MINIO_BUCKET=${MINIO_BUCKET}
    volumes:
      - mimir:/data
    restart: always

volumes:
  mimir:
    external: false
