services:
  mimir:
    build: .
    ports:
      - "${MIMIR_PORT}:8080"
    command: ["-config.file=/etc/mimir.yaml", "-config.expand-env=true"]
    environment:
      - MINIO_USER=${MIMIR_USER}
      - MINIO_PASSWORD=${MIMIR_PASSWORD}
    volumes:
      - mimir:/data
    restart: always

volumes:
  mimir:
    external: false
